### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by LinuxJedi** [svetasmirnova/run_external#1]
command is allocated but never free'd.  This can add up to a sizeable memory leak over the lifetime of the MySQL server.

**Comment by LinuxJedi** [comment]
As a side note, you could probably use a VLA instead and get rid of the allocation completely

**Comment by svetasmirnova** [comment]
Fixed by https://github.com/svetasmirnova/run_external/commit/ba8c26a336d93270fc43ad0ba1bbad573e8274a0
