### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by LinuxJedi** [svetasmirnova/run_external#6]
Whilst there is no LICENSE file and no license information in the head of the source files this is effectively commercial software with the source available for viewing. It makes it impossible to legally use it in many cases.

Please add a license to this software even if that license is a commercial one.

**Comment by svetasmirnova** [comment]
Added in revision https://github.com/svetasmirnova/run_external/commit/43ec46a5b91fd12e54967c7d9b94f68d2a501e61

BSD 3-clause license, compatible with GPL
